edition = "2021"

# Stable.
# fn_args_layout = "Compressed"
max_width = 100
use_field_init_shorthand = true
use_small_heuristics = "Max"

# Unstable (requires nightly rust).
comment_width = 100
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
# imports_layout = "Vertical"
wrap_comments = true
